services:
  dicom-watcher:
    container_name: dicom-watcher-app
    image: dicom-watcher-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
      - /devshares/shared_data_folder/katerina/dummy_data/dcm-folder/:/mnt/dcm-files/
    restart: unless-stopped
